project_name: fastly
release:
  prerelease: auto
before:
  hooks:
    - go mod tidy
    - go mod download
builds:
  - <<: &build_defaults
      main: ./cmd/fastly
      ldflags:
        - -s -w -X "github.com/fastly/cli/pkg/version.AppVersion={{ .Version }}"
        - -X "github.com/fastly/cli/pkg/version.GitRevision={{ .ShortCommit }}"
        - -X "github.com/fastly/cli/pkg/version.GoVersion={{ .Env.GOVERSION }}"
    id: macos
    goos: [darwin]
    goarch: [amd64]
  - <<: *build_defaults
    id: linux
    goos: [linux]
    goarch: [386, amd64, arm64]
  - <<: *build_defaults
    id: windows
    goos: [windows]
    goarch: [386, amd64]
archives:
  - id: nix
    builds: [macos, linux]
    <<: &archive_defaults
      name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
      files:
        - none*
    wrap_in_directory: false
    format: tar.gz
  - id: windows
    builds: [windows]
    <<: *archive_defaults
    wrap_in_directory: false
    format: zip
brews:
  - name: fastly
    ids: [nix]
    github:
      owner: fastly
      name: homebrew-tap
    skip_upload: auto
    description: Fastly CLI
    homepage: https://github.com/fastly/cli
    folder: Formula
    custom_block: |
      head do
        url "https://github.com/fastly/cli.git"
        depends_on "go"
      end
    install: |
      system "make" if build.head?
      bin.install "fastly"
      (bash_completion/"fastly.sh").write `#{bin}/fastly --completion-script-bash`
      (zsh_completion/"_fastly").write `#{bin}/fastly --completion-script-zsh`
    test: |
      help_text = shell_output("#{bin}/fastly --help")
      assert_includes help_text, "Usage:"
nfpms:
  - license: Apache 2.0
    maintainer: Fastly
    homepage: https://github.com/fastly/cli
    bindir: /usr/local/bin
    formats:
      - deb
      - rpm
scoop:
  bucket:
    owner: fastly
    name: scoop-cli
  homepage: https://github.com/fastly/cli
  skip_upload: auto
  description: Fastly CLI
  license: Apache 2.0
checksum:
  name_template: "{{ .ProjectName }}_v{{ .Version }}_SHA256SUMS"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
