project_name: fastly
release:
  prerelease: auto
before:
  hooks:
    - go mod tidy
    - go mod download
builds:
  - <<: &build_defaults
      main: ./cmd/fastly
      ldflags:
        - -s -w -X "github.com/fastly/cli/pkg/version.AppVersion={{ .Version }}"
        - -X "github.com/fastly/cli/pkg/version.GitRevision={{ .ShortCommit }}"
        - -X "github.com/fastly/cli/pkg/version.GoVersion={{ .Env.GOVERSION }}"
    id: macos
    goos: [darwin]
    goarch: [amd64]
  - <<: *build_defaults
    id: linux
    goos: [linux]
    goarch: [386, amd64, arm64]
  - <<: *build_defaults
    id: windows
    goos: [windows]
    goarch: [386, amd64]
archives:
  - id: nix
    builds: [macos, linux]
    <<: &archive_defaults
      name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: true
    format: tar.gz
  - id: windows
    builds: [windows]
    <<: *archive_defaults
    wrap_in_directory: false
    format: zip
checksum:
  name_template: "{{ .ProjectName }}_v{{ .Version }}_SHA256SUMS"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
