# docker build -t fastly/cli/assemblyscript . -f ./Dockerfile-assemblyscript

FROM node:latest

WORKDIR /tmp

RUN apt-get update && apt-get install -y jq

RUN export FASTLY_CLI_VERSION=$(curl --silent https://api.github.com/repos/fastly/cli/releases/latest | jq -r .tag_name | cut -d 'v' -f 2) \
  GOARCH=$(dpkg --print-architecture) \
  && curl -vL "https://github.com/fastly/cli/releases/download/v${FASTLY_CLI_VERSION}/fastly_v${FASTLY_CLI_VERSION}_linux-$GOARCH.tar.gz" -o fastly.tar.gz
RUN tar -xzf fastly.tar.gz
RUN mv fastly /usr/bin

RUN npm install --global npm@latest
RUN npm install --save-dev assemblyscript

WORKDIR /app
ENTRYPOINT ["/usr/bin/fastly"]
CMD ["--help"]
