FROM rust:1.51.0
LABEL maintainer="Fastly OSS <oss@fastly.com>"

ENV RUST_TOOLCHAIN=1.49.0
RUN rustup toolchain install ${RUST_TOOLCHAIN}
RUN rustup target add wasm32-wasi --toolchain ${RUST_TOOLCHAIN}

WORKDIR /tmp
RUN apt-get update && apt-get install -y curl jq
RUN export FASTLY_CLI_VERSION=$(curl --silent https://api.github.com/repos/fastly/cli/releases/latest | jq -r .tag_name | cut -d 'v' -f 2) \
  GOARCH=$(dpkg --print-architecture) \
  && curl -vL "https://github.com/fastly/cli/releases/download/v${FASTLY_CLI_VERSION}/fastly_v${FASTLY_CLI_VERSION}_linux-$GOARCH.tar.gz" -o fastly.tar.gz
RUN tar -xzf fastly.tar.gz
RUN mv fastly /usr/bin

WORKDIR /app
ENTRYPOINT ["/usr/bin/fastly"]
CMD ["--help"]

# docker build -t fastly/cli/rust . -f ./Dockerfile-rust
# docker run -it fastly/cli/rust
