FROM node:latest

WORKDIR /tmp

# NOTE: I have presumed we'd pass these env vars via the Docker -e flag.
RUN curl -L https://github.com/fastly/cli/releases/download/v${FASTLY_CLI_VERSION}/fastly_v${FASTLY_CLI_VERSION}_linux-${GOARCH}.tar.gz -o fastly.tgz
RUN tar -xzf fastly.tgz
RUN mv fastly /usr/bin

RUN npm init
RUN npm install --global npm@latest
RUN npm install --save-dev assemblyscript

WORKDIR /app
ENTRYPOINT ["/usr/bin/fastly"]
CMD ["--help"]
