# docker build -t fastly/cli/assemblyscript . -f ./Dockerfile-assemblyscript
# docker run -it fastly/cli/assemblyscript

FROM node:latest

COPY --from=fastly/cli /usr/bin/fastly /usr/bin/fastly

RUN npm install --global npm@latest
RUN npm install --save-dev assemblyscript

WORKDIR /app
ENTRYPOINT ["/usr/bin/fastly"]
CMD ["--help"]
