config_version = 2

[fastly]
api_endpoint = "https://api.fastly.com"

[cli]
remote_config = "https://developer.fastly.com/api/internal/cli-config"
ttl = "5m"

[language]
  [language.rust]
  toolchain_version = "1.54.0"
  toolchain_constraint = ">= 1.54.0"
  wasm_wasi_target = "wasm32-wasi"
  fastly_sys_constraint = ">= 0.3.3"
  rustup_constraint = ">= 1.23.0"

[starter-kits]
[[starter-kits.assemblyscript]]
  name = "Default"
  path = "https://github.com/fastly/compute-starter-kit-assemblyscript-default"
[[starter-kits.javascript]]
  name = "Default"
  path = "https://github.com/fastly/compute-starter-kit-javascript-default"
[[starter-kits.rust]]
  name = "Default"
  path = "https://github.com/fastly/compute-starter-kit-rust-default"
[[starter-kits.rust]]
  name = "Beacon"
  path = "https://github.com/fastly/compute-starter-kit-rust-beacon-termination"
[[starter-kits.rust]]
  name = "Static"
  path = "https://github.com/fastly/compute-starter-kit-rust-static-content"
