package env

import (
	"fmt"
	"os"
	"strings"

	"github.com/fastly/cli/v10/pkg/runtime"
)

const (
	// AccountEndpoint is the env var we look in for the Accounts endpoint.
	// e.g. https://accounts.fastly.com
	AccountEndpoint = "FASTLY_ACCOUNT_ENDPOINT"

	// APIEndpoint is the env var we look in for the API endpoint.
	// e.g. https://api.fastly.com
	APIEndpoint = "FASTLY_API_ENDPOINT"

	// APIToken is the env var we look in for the Fastly API token.
	// gosec flagged this:
	// G101 (CWE-798): Potential hardcoded credentials
	// Disabling as we use the value in the command help output.
	// #nosec
	APIToken = "FASTLY_API_TOKEN"

	// CustomerID is the env var we look in for a Customer ID.
	CustomerID = "FASTLY_CUSTOMER_ID"

	// DebugMode indicates to the CLI it can display debug information.
	// Set to "true" to enable debug mode.
	DebugMode = "FASTLY_DEBUG_MODE"

	// ServiceID is the env var we look in for the required Service ID.
	ServiceID = "FASTLY_SERVICE_ID"

	// UseSSO enables the CLI to validate the token as an OAuth token.
	// These tokens aren't traditional tokens generated by the UI.
	// Instead they generated via an OAuth flow (producing access/refresh tokens).
	// Assigned value should be a boolean 1/0 (enable/disable).
	UseSSO = "FASTLY_USE_SSO"

	// WasmMetadataDisable is the env var we look in to disable all data
	// collection related to a Wasm binary.
	// Set to "true" to disable all forms of data collection.
	WasmMetadataDisable = "FASTLY_WASM_METADATA_DISABLE"
)

// Parse transforms the local environment data structure into a map type.
func Parse(environ []string) map[string]string {
	env := map[string]string{}
	for _, kv := range environ {
		k, v, ok := strings.Cut(kv, "=")
		if !ok {
			continue
		}
		env[k] = v
	}
	return env
}

// Vars returns a slice of environment variables appropriate to platform.
// *nix: $HOME, $USER, ...
// Windows: %HOME%, %USER%, ...
func Vars() []string {
	vars := []string{}
	for _, e := range os.Environ() {
		pair := strings.SplitN(e, "=", 2)
		vars = append(vars, toVar(pair[0]))
	}
	return vars
}

func toVar(v string) string {
	if runtime.Windows {
		return toWin(v)
	}
	return toNix(v)
}

func toNix(v string) string {
	return fmt.Sprintf("\\$%s", v)
}

func toWin(v string) string {
	return fmt.Sprintf("%%%s%%", v)
}
