package compute_test

import (
	"bytes"
	"context"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/fastly/cli/pkg/app"
	"github.com/fastly/cli/pkg/commands/compute"
	"github.com/fastly/cli/pkg/errors"
	"github.com/fastly/cli/pkg/manifest"
	"github.com/fastly/cli/pkg/mock"
	"github.com/fastly/cli/pkg/testutil"
	"github.com/fastly/go-fastly/v6/fastly"
)

// NOTE: Some tests don't provide a Service ID via any mechanism (e.g. flag
// or manifest) and if one is provided the test will fail due to a specific
// API call not being mocked. Be careful not to add a Service ID to all tests
// without first checking whether the Service ID is expected as the user flow
// for when no Service ID is provided is to create a new service.
//
// Additionally, stdin can be mocked in one of two ways...
//
// 1. Provide a single value.
// 2. Provide multiple values (one for each prompt expected).
//
// In the first case, the first prompt given to the user will get the value you
// defined in the testcase.stdin field, all other prompts will get an empty
// value. This has worked fine for the most part as the prompts have
// historically provided default values when an empty value is encountered.
//
// The second case is to address running the test code successfully as the
// business logic has changed over time to now 'require' values to be provided
// for some prompts, this means an empty string will break the test flow. If
// that's what you're encountering, then you should add multiple values for the
// testcase.stdin field so that there is a value provided for every prompt your
// testcase user flow expects to encounter.
func TestDeploy(t *testing.T) {
	if os.Getenv("TEST_COMPUTE_DEPLOY") == "" {
		t.Log("skipping test")
		t.Skip("Set TEST_COMPUTE_DEPLOY to run this test")
	}

	// We're going to chdir to a deploy environment,
	// so save the PWD to return to, afterwards.
	pwd, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}

	// Create test environment
	rootdir := testutil.NewEnv(testutil.EnvOpts{
		T: t,
		Copy: []testutil.FileIO{
			{
				Src: filepath.Join("testdata", "deploy", "pkg", "package.tar.gz"),
				Dst: filepath.Join("pkg", "package.tar.gz"),
			},
		},
	})
	defer os.RemoveAll(rootdir)

	// Before running the test, chdir into the build environment.
	// When we're done, chdir back to our original location.
	// This is so we can reliably copy the testdata/ fixtures.
	if err := os.Chdir(rootdir); err != nil {
		t.Fatal(err)
	}
	defer os.Chdir(pwd)

	originalPackageSizeLimit := compute.PackageSizeLimit
	args := testutil.Args
	for _, testcase := range []struct {
		api                  mock.API
		args                 []string
		dontWantOutput       []string
		httpClientRes        *http.Response
		httpClientErr        error
		manifest             string
		name                 string
		noManifest           bool
		reduceSizeLimit      bool
		stdin                []string
		wantError            string
		wantRemediationError string
		wantOutput           []string
	}{
		{
			name:      "no token",
			args:      args("compute deploy"),
			wantError: "no token provided",
		},
		{
			name:                 "no fastly.toml manifest",
			args:                 args("compute deploy --token 123"),
			wantError:            "error reading package manifest",
			wantRemediationError: errors.ComputeInitRemediation,
			noManifest:           true,
		},
		{
			// If no Service ID defined via flag or manifest, then the expectation is
			// for the service to be created via the API and for the returned ID to
			// be stored into the manifest.
			//
			// Additionally it validates that the specified path (files generated by
			// the testutil.NewEnv()) cause no issues.
			name: "path with no service ID",
			args: args("compute deploy --token 123 -v --package pkg/package.tar.gz"),
			api: mock.API{
				ActivateVersionFn: activateVersionOk,
				CreateBackendFn:   createBackendOK,
				CreateDomainFn:    createDomainOK,
				CreateServiceFn:   createServiceOK,
				GetPackageFn:      getPackageOk,
				ListDomainsFn:     listDomainsOk,
				UpdatePackageFn:   updatePackageOk,
			},
			stdin: []string{
				"Y", // when prompted to create a new service
			},
			wantOutput: []string{
				"Deployed package (service 12345, version 1)",
			},
		},
		// Same validation as above with the exception that we use the default path
		// parsing logic (i.e. we don't explicitly pass a path via `-p` flag).
		{
			name: "empty service ID",
			args: args("compute deploy --token 123 -v"),
			api: mock.API{
				ActivateVersionFn: activateVersionOk,
				CreateBackendFn:   createBackendOK,
				CreateDomainFn:    createDomainOK,
				CreateServiceFn:   createServiceOK,
				GetPackageFn:      getPackageOk,
				ListDomainsFn:     listDomainsOk,
				UpdatePackageFn:   updatePackageOk,
			},
			stdin: []string{
				"Y", // when prompted to create a new service
			},
			wantOutput: []string{
				"Deployed package (service 12345, version 1)",
			},
		},
		{
			name: "list versions error",
			args: args("compute deploy --service-id 123 --token 123"),
			api: mock.API{
				GetServiceFn:   getServiceOK,
				ListVersionsFn: testutil.ListVersionsError,
			},
			wantError: fmt.Sprintf("error listing service versions: %s", testutil.Err.Error()),
		},
		{
			name: "service version is active, clone version error",
			args: args("compute deploy --service-id 123 --token 123 --version 1"),
			api: mock.API{
				CloneVersionFn:      testutil.CloneVersionError,
				GetServiceDetailsFn: getServiceDetailsWasm,
				ListVersionsFn:      testutil.ListVersions,
			},
			wantError: fmt.Sprintf("error cloning service version: %s", testutil.Err.Error()),
		},
		{
			name: "list domains error",
			args: args("compute deploy --service-id 123 --token 123"),
			api: mock.API{
				GetServiceDetailsFn: getServiceDetailsWasm,
				GetServiceFn:        getServiceOK,
				ListDomainsFn:       listDomainsError,
				ListVersionsFn:      testutil.ListVersions,
			},
			wantError: fmt.Sprintf("error fetching service domains: %s", testutil.Err.Error()),
		},
		{
			name:                 "package size too large",
			args:                 args("compute deploy --package pkg/package.tar.gz --token 123"),
			reduceSizeLimit:      true,
			wantError:            "package size is too large",
			wantRemediationError: errors.PackageSizeRemediation,
		},
		// The following test doesn't just validate the package API error behaviour
		// but as a side effect it validates that when deleting the created
		// service, the Service ID is also cleared out from the manifest.
		{
			name: "package API error",
			args: args("compute deploy --token 123"),
			api: mock.API{
				CreateBackendFn: createBackendOK,
				CreateDomainFn:  createDomainOK,
				CreateServiceFn: createServiceOK,
				DeleteBackendFn: deleteBackendOK,
				DeleteDomainFn:  deleteDomainOK,
				DeleteServiceFn: deleteServiceOK,
				GetPackageFn:    getPackageOk,
				ListDomainsFn:   listDomainsOk,
				UpdatePackageFn: updatePackageError,
			},
			stdin: []string{
				"Y", // when prompted to create a new service
			},
			wantError: fmt.Sprintf("error uploading package: %s", testutil.Err.Error()),
			wantOutput: []string{
				"Uploading package...",
			},
		},
		// The following test doesn't provide a Service ID by either a flag nor the
		// manifest, so this will result in the deploy script attempting to create
		// a new service. We mock the API call to fail, and we expect to see a
		// relevant error message related to that error.
		{
			name: "service create error",
			args: args("compute deploy --token 123"),
			api: mock.API{
				CreateServiceFn: createServiceError,
			},
			stdin: []string{
				"Y", // when prompted to create a new service
			},
			wantError: fmt.Sprintf("error creating service: %s", testutil.Err.Error()),
			wantOutput: []string{
				"Creating service...",
			},
		},
		// The following test mocks the service creation to fail with a specific
		// error value that will result in the code trying to activate a free trial
		// for the customer's account.
		//
		// Specifically this test will fail the initial API call to get the
		// customer's details and so we expect it to return that error (as we can't
		// activate a free trial without knowing the customer ID).
		{
			name: "service create error due to no trial activated and error getting user",
			args: args("compute deploy --token 123"),
			api: mock.API{
				CreateServiceFn:  createServiceErrorNoTrial,
				GetCurrentUserFn: getCurrentUserError,
			},
			stdin: []string{
				"Y", // when prompted to create a new service
			},
			wantError: fmt.Sprintf("unable to identify user associated with the given token: %s", testutil.Err.Error()),
			wantOutput: []string{
				"Creating service...",
			},
		},
		// The following test mocks the HTTP client to return a 400 Bad Request,
		// which is then coerced into a generic 'no free trial' error.
		{
			name: "service create error due to no trial activated and error activating trial",
			args: args("compute deploy --token 123"),
			api: mock.API{
				CreateServiceFn:  createServiceErrorNoTrial,
				GetCurrentUserFn: getCurrentUser,
			},
			httpClientRes: &http.Response{
				Body:       io.NopCloser(strings.NewReader(testutil.Err.Error())),
				Status:     http.StatusText(http.StatusBadRequest),
				StatusCode: http.StatusBadRequest,
			},
			httpClientErr: nil,
			stdin: []string{
				"Y", // when prompted to create a new service
			},
			wantError:            "error creating service: you do not have the Compute@Edge free trial enabled on your Fastly account",
			wantRemediationError: errors.ComputeTrialRemediation,
			wantOutput: []string{
				"Creating service...",
			},
		},
		// The following test mocks the HTTP client to return a timeout error,
		// which is then coerced into a generic 'no free trial' error.
		{
			name: "service create error due to no trial activated and activating trial timeout",
			args: args("compute deploy --token 123"),
			api: mock.API{
				CreateServiceFn:  createServiceErrorNoTrial,
				GetCurrentUserFn: getCurrentUser,
			},
			httpClientRes: nil,
			httpClientErr: &url.Error{Err: context.DeadlineExceeded},
			stdin: []string{
				"Y", // when prompted to create a new service
			},
			wantError:            "error creating service: you do not have the Compute@Edge free trial enabled on your Fastly account",
			wantRemediationError: errors.ComputeTrialRemediation,
			wantOutput: []string{
				"Creating service...",
			},
		},
		// The following test mocks the HTTP client to return successfully when
		// trying to activate the free trial.
		{
			name: "service create success",
			args: args("compute deploy --token 123"),
			api: mock.API{
				ActivateVersionFn: activateVersionOk,
				CreateBackendFn:   createBackendOK,
				CreateServiceFn:   createServiceOK,
				GetPackageFn:      getPackageOk,
				ListDomainsFn:     listDomainsOk,
				UpdatePackageFn:   updatePackageOk,
			},
			httpClientRes: &http.Response{
				Body:       io.NopCloser(strings.NewReader("success")),
				Status:     http.StatusText(http.StatusOK),
				StatusCode: http.StatusOK,
			},
			httpClientErr: nil,
			stdin: []string{
				"Y", // when prompted to create a new service
			},
			wantOutput: []string{
				"Creating service...",
			},
		},
		// The following test doesn't provide a Service ID by either a flag nor the
		// manifest, so this will result in the deploy script attempting to create
		// a new service. We mock the service creation to be successful while we
		// mock the domain API call to fail, and we expect to see a relevant error
		// message related to that error.
		{
			name: "service domain error",
			args: args("compute deploy --token 123"),
			api: mock.API{
				CreateDomainFn:  createDomainError,
				CreateServiceFn: createServiceOK,
				DeleteDomainFn:  deleteDomainOK,
				DeleteServiceFn: deleteServiceOK,
				ListDomainsFn:   listDomainsNone,
			},
			stdin: []string{
				"Y", // when prompted to create a new service
			},
			wantError: fmt.Sprintf("error creating domain: %s", testutil.Err.Error()),
			wantOutput: []string{
				"Creating service...",
				"Creating domain '",
			},
		},
		// The following test doesn't provide a Service ID by either a flag nor the
		// manifest, so this will result in the deploy script attempting to create
		// a new service. We mock the service creation to be successful while we
		// mock the backend API call to succeed but to return an unexpected empty
		// list of Backends.
		{
			name: "service backend error",
			args: args("compute deploy --token 123"),
			api: mock.API{
				CreateBackendFn: createBackendError,
				CreateDomainFn:  createDomainOK,
				CreateServiceFn: createServiceOK,
				DeleteBackendFn: deleteBackendOK,
				DeleteDomainFn:  deleteDomainOK,
				DeleteServiceFn: deleteServiceOK,
				ListDomainsFn:   listDomainsOk,
			},
			stdin: []string{
				"Y", // when prompted to create a new service
			},
			wantError: fmt.Sprintf("error configuring the service: %s", testutil.Err.Error()),
			wantOutput: []string{
				"Creating service...",
			},
			dontWantOutput: []string{
				"Creating domain '",
			},
		},
		// The following test validates that the undoStack is executed as expected
		// e.g. the backend and domain resources are deleted.
		{
			name: "activate error",
			args: args("compute deploy --service-id 123 --token 123"),
			api: mock.API{
				ActivateVersionFn:   activateVersionError,
				CreateDomainFn:      createDomainOK,
				DeleteDomainFn:      deleteDomainOK,
				GetPackageFn:        getPackageOk,
				GetServiceFn:        getServiceOK,
				GetServiceDetailsFn: getServiceDetailsWasm,
				ListDomainsFn:       listDomainsNone,
				ListVersionsFn:      testutil.ListVersions,
				UpdatePackageFn:     updatePackageOk,
			},
			wantError: fmt.Sprintf("error activating version: %s", testutil.Err.Error()),
			wantOutput: []string{
				"Creating domain '",
				"Uploading package...",
				"Activating version...",
			},
		},
		// The following test validates that if a package contains code that has
		// not changed since the last deploy, then the deployment is skipped.
		{
			name: "identical package",
			args: args("compute deploy --service-id 123 --token 123"),
			api: mock.API{
				GetPackageFn:        getPackageIdentical,
				GetServiceFn:        getServiceOK,
				GetServiceDetailsFn: getServiceDetailsWasm,
				ListDomainsFn:       listDomainsOk,
				ListVersionsFn:      testutil.ListVersions,
			},
			wantOutput: []string{
				"Skipping package deployment",
			},
		},
		{
			name: "success with existing service",
			args: args("compute deploy --service-id 123 --token 123"),
			api: mock.API{
				ActivateVersionFn:   activateVersionOk,
				GetPackageFn:        getPackageOk,
				GetServiceFn:        getServiceOK,
				GetServiceDetailsFn: getServiceDetailsWasm,
				ListDomainsFn:       listDomainsOk,
				ListVersionsFn:      testutil.ListVersions,
				UpdatePackageFn:     updatePackageOk,
			},
			wantOutput: []string{
				"Uploading package...",
				"Activating version...",
				"Manage this service at:",
				"https://manage.fastly.com/configure/services/123",
				"View this service at:",
				"https://directly-careful-coyote.edgecompute.app",
				"Deployed package (service 123, version 3)",
			},
		},
		{
			name: "success with path",
			args: args("compute deploy --service-id 123 --token 123 --package pkg/package.tar.gz --version latest"),
			api: mock.API{
				ActivateVersionFn:   activateVersionOk,
				GetPackageFn:        getPackageOk,
				GetServiceFn:        getServiceOK,
				GetServiceDetailsFn: getServiceDetailsWasm,
				ListDomainsFn:       listDomainsOk,
				ListVersionsFn:      testutil.ListVersions,
				UpdatePackageFn:     updatePackageOk,
			},
			wantOutput: []string{
				"Uploading package...",
				"Activating version...",
				"Manage this service at:",
				"https://manage.fastly.com/configure/services/123",
				"View this service at:",
				"https://directly-careful-coyote.edgecompute.app",
				"Deployed package (service 123, version 3)",
			},
		},
		// NOTE: The following test ensures that if the user runs the CLI from a
		// directory that isn't a C@E project directory (i.e. it has no manifest
		// file present) then the deploy command should try to locate a manifest
		// inside the given package tar.gz archive.
		{
			name: "success with path called from non project directory",
			args: args("compute deploy --service-id 123 --token 123 --package pkg/package.tar.gz --version latest"),
			api: mock.API{
				ActivateVersionFn:   activateVersionOk,
				GetPackageFn:        getPackageOk,
				GetServiceFn:        getServiceOK,
				GetServiceDetailsFn: getServiceDetailsWasm,
				ListDomainsFn:       listDomainsOk,
				ListVersionsFn:      testutil.ListVersions,
				UpdatePackageFn:     updatePackageOk,
			},
			noManifest: true,
			wantOutput: []string{
				"Using fastly.toml within --package archive:",
				"Uploading package...",
				"Activating version...",
				"Manage this service at:",
				"https://manage.fastly.com/configure/services/123",
				"View this service at:",
				"https://directly-careful-coyote.edgecompute.app",
				"Deployed package (service 123, version 3)",
			},
		},
		{
			name: "success with inactive version",
			args: args("compute deploy --service-id 123 --token 123 --package pkg/package.tar.gz"),
			api: mock.API{
				ActivateVersionFn:   activateVersionOk,
				GetPackageFn:        getPackageOk,
				GetServiceFn:        getServiceOK,
				GetServiceDetailsFn: getServiceDetailsWasm,
				ListDomainsFn:       listDomainsOk,
				ListVersionsFn:      testutil.ListVersions,
				UpdatePackageFn:     updatePackageOk,
			},
			wantOutput: []string{
				"Uploading package...",
				"Activating version...",
				"Deployed package (service 123, version 3)",
			},
		},
		{
			name: "success with specific locked version",
			args: args("compute deploy --service-id 123 --token 123 --package pkg/package.tar.gz --version 2"),
			api: mock.API{
				ActivateVersionFn:   activateVersionOk,
				CloneVersionFn:      testutil.CloneVersionResult(4),
				GetPackageFn:        getPackageOk,
				GetServiceFn:        getServiceOK,
				GetServiceDetailsFn: getServiceDetailsWasm,
				ListDomainsFn:       listDomainsOk,
				ListVersionsFn:      testutil.ListVersions,
				UpdatePackageFn:     updatePackageOk,
			},
			wantOutput: []string{
				"Uploading package...",
				"Activating version...",
				"Deployed package (service 123, version 4)",
			},
		},
		{
			name: "success with active version",
			args: args("compute deploy --service-id 123 --token 123 --package pkg/package.tar.gz --version active"),
			api: mock.API{
				ActivateVersionFn:   activateVersionOk,
				CloneVersionFn:      testutil.CloneVersionResult(4),
				GetPackageFn:        getPackageOk,
				GetServiceFn:        getServiceOK,
				GetServiceDetailsFn: getServiceDetailsWasm,
				ListDomainsFn:       listDomainsOk,
				ListVersionsFn:      testutil.ListVersions,
				UpdatePackageFn:     updatePackageOk,
			},
			wantOutput: []string{
				"Uploading package...",
				"Activating version...",
				"Deployed package (service 123, version 4)",
			},
		},
		{
			name: "success with comment",
			args: args("compute deploy --service-id 123 --token 123 --package pkg/package.tar.gz --version 2 --comment foo"),
			api: mock.API{
				ActivateVersionFn:   activateVersionOk,
				CloneVersionFn:      testutil.CloneVersionResult(4),
				GetPackageFn:        getPackageOk,
				GetServiceFn:        getServiceOK,
				GetServiceDetailsFn: getServiceDetailsWasm,
				ListDomainsFn:       listDomainsOk,
				ListVersionsFn:      testutil.ListVersions,
				UpdatePackageFn:     updatePackageOk,
				UpdateVersionFn:     updateVersionOk,
			},
			wantOutput: []string{
				"Uploading package...",
				"Activating version...",
				"Deployed package (service 123, version 4)",
			},
		},
		// The following test doesn't provide a Service ID by either a flag nor the
		// manifest, so this will result in the deploy script attempting to create
		// a new service. Our fastly.toml is configured with a [setup] section so
		// we expect to see the appropriate messaging in the output.
		{
			name: "success with setup.backends configuration",
			args: args("compute deploy --token 123"),
			api: mock.API{
				ActivateVersionFn: activateVersionOk,
				CreateBackendFn:   createBackendOK,
				CreateDomainFn:    createDomainOK,
				CreateServiceFn:   createServiceOK,
				GetPackageFn:      getPackageOk,
				ListDomainsFn:     listDomainsOk,
				UpdatePackageFn:   updatePackageOk,
			},
			manifest: `
			name = "package"
			manifest_version = 2
			language = "rust"

			[setup.backends.backend_name]
			prompt = "Backend 1"
			address = "developer.fastly.com"
			port = 443
			[setup.backends.other_backend_name]
			prompt = "Backend 2"
			address = "httpbin.org"
			port = 443
			`,
			stdin: []string{
				"Y", // when prompted to create a new service
			},
			wantOutput: []string{
				"Hostname or IP address: [developer.fastly.com]",
				"Port: [443]",
				"Hostname or IP address: [httpbin.org]",
				"Port: [443]",
				"Creating service...",
				"Creating backend 'backend_name' (host: developer.fastly.com, port: 443)...",
				"Creating backend 'other_backend_name' (host: httpbin.org, port: 443)...",
				"Uploading package...",
				"Activating version...",
				"SUCCESS: Deployed package (service 12345, version 1)",
			},
		},
		// The following [setup] configuration doesn't define any prompts, nor any
		// ports, so we validate that the user prompts match our default expectations.
		{
			name: "success with setup.backends configuration and no prompts or ports defined",
			args: args("compute deploy --token 123"),
			api: mock.API{
				ActivateVersionFn: activateVersionOk,
				CreateBackendFn:   createBackendOK,
				CreateDomainFn:    createDomainOK,
				CreateServiceFn:   createServiceOK,
				GetPackageFn:      getPackageOk,
				ListDomainsFn:     listDomainsOk,
				UpdatePackageFn:   updatePackageOk,
			},
			manifest: `
			name = "package"
			manifest_version = 2
			language = "rust"

			[setup.backends.foo_backend]
			address = "developer.fastly.com"
			[setup.backends.bar_backend]
			address = "httpbin.org"
			`,
			stdin: []string{
				"Y", // when prompted to create a new service
			},
			wantOutput: []string{
				"Hostname or IP address: [developer.fastly.com]",
				"Port: [80]",
				"Hostname or IP address: [httpbin.org]",
				"Port: [80]",
				"Creating service...",
				"Creating backend 'foo_backend' (host: developer.fastly.com, port: 80)...",
				"Creating backend 'bar_backend' (host: httpbin.org, port: 80)...",
				"Uploading package...",
				"Activating version...",
				"SUCCESS: Deployed package (service 12345, version 1)",
			},
			dontWantOutput: []string{
				"Creating domain '",
			},
		},
		{
			name: "success with setup.backends configuration but no fields for the required resources",
			args: args("compute deploy --token 123"),
			api: mock.API{
				ActivateVersionFn: activateVersionOk,
				CreateBackendFn:   createBackendOK,
				CreateDomainFn:    createDomainOK,
				CreateServiceFn:   createServiceOK,
				GetPackageFn:      getPackageOk,
				ListDomainsFn:     listDomainsOk,
				UpdatePackageFn:   updatePackageOk,
			},
			manifest: `
			name = "package"
			manifest_version = 2
			language = "rust"

			[setup.backends.foo_backend]
			[setup.backends.bar_backend]
			`,
			stdin: []string{
				"Y", // when prompted to create a new service
			},
			wantOutput: []string{
				"Configure a backend called 'foo_backend'",
				"Hostname or IP address: [127.0.0.1]",
				"Port: [80]",
				"Configure a backend called 'bar_backend'",
				"Hostname or IP address: [127.0.0.1]",
				"Port: [80]",
				"Creating service...",
				"Creating backend 'foo_backend' (host: 127.0.0.1, port: 80)...",
				"Creating backend 'bar_backend' (host: 127.0.0.1, port: 80)...",
				"Uploading package...",
				"Activating version...",
				"SUCCESS: Deployed package (service 12345, version 1)",
			},
			dontWantOutput: []string{
				"Creating domain '",
			},
		},
		// The following test validates no prompts are displayed to the user due to
		// the use of the --non-interactive flag.
		{
			name: "success with setup.backends configuration and accept-defaults",
			args: args("compute deploy --non-interactive --token 123"),
			api: mock.API{
				ActivateVersionFn: activateVersionOk,
				CreateBackendFn:   createBackendOK,
				CreateDomainFn:    createDomainOK,
				CreateServiceFn:   createServiceOK,
				GetPackageFn:      getPackageOk,
				ListDomainsFn:     listDomainsOk,
				UpdatePackageFn:   updatePackageOk,
			},
			manifest: `
			name = "package"
			manifest_version = 2
			language = "rust"

			[setup.backends.backend_name]
			description = "Backend 1"
			address = "developer.fastly.com"
			port = 443
			[setup.backends.other_backend_name]
			description = "Backend 2"
			address = "httpbin.org"
			port = 443
			`,
			wantOutput: []string{
				"Initializing...",
				"Creating service...",
				"Creating backend 'backend_name' (host: developer.fastly.com, port: 443)...",
				"Creating backend 'other_backend_name' (host: httpbin.org, port: 443)...",
				"Uploading package...",
				"Activating version...",
				"SUCCESS: Deployed package (service 12345, version 1)",
			},
			dontWantOutput: []string{
				"Backend 1: [developer.fastly.com]",
				"Backend port number: [443]",
				"Backend 2: [httpbin.org]",
				"Backend port number: [443]",
				"Domain: [",
			},
		},
		// The following test validates that a new 'originless' backend is created
		// when the user has no [setup] configuration and they also pass the
		// --non-interactive flag. This is done by ensuring we DON'T see the
		// standard 'Creating backend' output because we want to conceal the fact
		// that we require a backend for compute services because it's a temporary
		// implementation detail.
		{
			name: "success with no setup.backends configuration and non-interactive for new service creation",
			args: args("compute deploy --non-interactive --token 123"),
			api: mock.API{
				ActivateVersionFn: activateVersionOk,
				CreateBackendFn:   createBackendOK,
				CreateDomainFn:    createDomainOK,
				CreateServiceFn:   createServiceOK,
				GetPackageFn:      getPackageOk,
				ListDomainsFn:     listDomainsOk,
				UpdatePackageFn:   updatePackageOk,
			},
			wantOutput: []string{
				"SUCCESS: Deployed package (service 12345, version 1)",
			},
			dontWantOutput: []string{
				"Creating backend", // expect originless creation to be hidden
			},
		},
		{
			name: "success with no setup.backends configuration and single backend entered at prompt for new service",
			args: args("compute deploy --token 123"),
			api: mock.API{
				ActivateVersionFn: activateVersionOk,
				CreateBackendFn:   createBackendOK,
				CreateDomainFn:    createDomainOK,
				CreateServiceFn:   createServiceOK,
				GetPackageFn:      getPackageOk,
				ListDomainsFn:     listDomainsOk,
				UpdatePackageFn:   updatePackageOk,
			},
			stdin: []string{
				"Y", // when prompted to create a new service
				"fastly.com",
				"443",
				"my_backend_name",
				"", // this stops prompting for backends
			},
			wantOutput: []string{
				"Backend (hostname or IP address, or leave blank to stop adding backends):",
				"Backend port number: [80]",
				"Backend name:",
				"Creating backend 'my_backend_name' (host: fastly.com, port: 443)...",
				"SUCCESS: Deployed package (service 12345, version 1)",
			},
		},
		// This is the same test as above but when prompted it will provide two
		// backends instead of one, and will also allow the code to generate the
		// backend name using its predefined formula.
		{
			name: "success with no setup.backends configuration and multiple backends entered at prompt for new service",
			args: args("compute deploy --token 123"),
			api: mock.API{
				ActivateVersionFn: activateVersionOk,
				CreateBackendFn:   createBackendOK,
				CreateDomainFn:    createDomainOK,
				CreateServiceFn:   createServiceOK,
				GetPackageFn:      getPackageOk,
				ListDomainsFn:     listDomainsOk,
				UpdatePackageFn:   updatePackageOk,
			},
			stdin: []string{
				"Y", // when prompted to create a new service
				"fastly.com",
				"443",
				"", // this is so we generate a backend name using a built-in formula
				"google.com",
				"123",
				"", // this is so we generate a backend name using a built-in formula
				"", // this stops prompting for backends
			},
			wantOutput: []string{
				"Backend (hostname or IP address, or leave blank to stop adding backends):",
				"Backend port number: [80]",
				"Backend name:",
				"Creating backend 'backend_1' (host: fastly.com, port: 443)...",
				"Creating backend 'backend_2' (host: google.com, port: 123)...",
				"SUCCESS: Deployed package (service 12345, version 1)",
			},
		},
		// The following test validates that when prompting the user for backends
		// that we'll default to creating an 'originless' backend if no value
		// provided at the prompt.
		{
			name: "success with no setup.backends configuration and defaulting to originless",
			args: args("compute deploy --token 123"),
			api: mock.API{
				ActivateVersionFn: activateVersionOk,
				CreateBackendFn:   createBackendOK,
				CreateDomainFn:    createDomainOK,
				CreateServiceFn:   createServiceOK,
				GetPackageFn:      getPackageOk,
				ListDomainsFn:     listDomainsOk,
				UpdatePackageFn:   updatePackageOk,
			},
			stdin: []string{
				"Y", // when prompted to create a new service
				"",  // this stops prompting for backends
			},
			wantOutput: []string{
				"Backend (hostname or IP address, or leave blank to stop adding backends):",
				"SUCCESS: Deployed package (service 12345, version 1)",
			},
			dontWantOutput: []string{
				"Creating backend", // expect originless creation to be hidden
			},
		},
		// The following test is the same setup as above, but if the user provides
		// the --non-interactive flag we won't prompt for any backends.
		{
			name: "success with no setup.backends configuration and use of --non-interactive",
			args: args("compute deploy --non-interactive --token 123"),
			api: mock.API{
				ActivateVersionFn:   activateVersionOk,
				CreateBackendFn:     createBackendOK,
				CreateServiceFn:     createServiceOK,
				GetPackageFn:        getPackageOk,
				GetServiceFn:        getServiceOK,
				GetServiceDetailsFn: getServiceDetailsWasm,
				ListDomainsFn:       listDomainsOk,
				ListVersionsFn:      testutil.ListVersions,
				UpdatePackageFn:     updatePackageOk,
			},
			wantOutput: []string{
				"SUCCESS: Deployed package (service 12345, version 1)",
			},
			dontWantOutput: []string{
				"Create new service",
				"Creating backend", // expect originless creation to be hidden
			},
		},
		// The following test validates that when dealing with an existing service,
		// no [setup.backends] configuration is utilised.
		//
		// i.e. we will not validate the service for missing backends, nor will we
		// prompt the user to create any backends.
		{
			name: "success with setup.backends configuration and existing service",
			args: args("compute deploy --service-id 123 --token 123"),
			api: mock.API{
				ActivateVersionFn:   activateVersionOk,
				CreateBackendFn:     createBackendOK,
				GetPackageFn:        getPackageOk,
				GetServiceFn:        getServiceOK,
				GetServiceDetailsFn: getServiceDetailsWasm,
				ListDomainsFn:       listDomainsOk,
				ListVersionsFn:      testutil.ListVersions,
				UpdatePackageFn:     updatePackageOk,
			},
			manifest: `
			name = "package"
			manifest_version = 2
			language = "rust"

			[setup.backends.fastly]
			description = "Backend 1"
			address = "fastly.com"
			port = 443
			[setup.backends.google]
			description = "Backend 2"
			address = "google.com"
			port = 443
			[setup.backends.facebook]
			description = "Backend 3"
			address = "facebook.com"
			port = 443
			`,
			wantOutput: []string{
				"Uploading package...",
				"Activating version...",
				"SUCCESS: Deployed package (service 123, version 3)",
			},
			dontWantOutput: []string{
				"Creating backend 'google' (host: beep.com, port: 123)",
				"Creating backend 'facebook' (host: boop.com, port: 456)",
			},
		},
		{
			name: "success with setup.dictionaries configuration and existing service",
			args: args("compute deploy --service-id 123 --token 123"),
			api: mock.API{
				ActivateVersionFn:   activateVersionOk,
				CreateBackendFn:     createBackendOK,
				GetPackageFn:        getPackageOk,
				GetServiceFn:        getServiceOK,
				GetServiceDetailsFn: getServiceDetailsWasm,
				ListDomainsFn:       listDomainsOk,
				ListVersionsFn:      testutil.ListVersions,
				UpdatePackageFn:     updatePackageOk,
			},
			manifest: `
			name = "package"
			manifest_version = 2
			language = "rust"

			[setup.dictionaries.dict_a]
			description = "My first dictionary"
			[setup.dictionaries.dict_a.items.foo]
			value = "my default value for foo"
			description = "a good description about foo"
			[setup.dictionaries.dict_a.items.bar]
			value = "my default value for bar"
			description = "a good description about bar"
			`,
			wantOutput: []string{
				"Uploading package...",
				"Activating version...",
				"SUCCESS: Deployed package (service 123, version 3)",
			},
			dontWantOutput: []string{
				"Configuring dictionary 'dict_a'",
				"Create a dictionary key called 'foo'",
				"Create a dictionary key called 'bar'",
				"Creating dictionary 'dict_a'...",
				"Creating dictionary item 'foo'...",
				"Creating dictionary item 'bar'...",
			},
		},
		{
			name: "success with setup.dictionaries configuration and no existing service",
			args: args("compute deploy --token 123"),
			api: mock.API{
				ActivateVersionFn:      activateVersionOk,
				CreateBackendFn:        createBackendOK,
				CreateDictionaryFn:     createDictionaryOK,
				CreateDictionaryItemFn: createDictionaryItemOK,
				CreateDomainFn:         createDomainOK,
				CreateServiceFn:        createServiceOK,
				GetPackageFn:           getPackageOk,
				GetServiceFn:           getServiceOK,
				GetServiceDetailsFn:    getServiceDetailsWasm,
				ListDomainsFn:          listDomainsOk,
				ListVersionsFn:         testutil.ListVersions,
				UpdatePackageFn:        updatePackageOk,
			},
			manifest: `
			name = "package"
			manifest_version = 2
			language = "rust"

			[setup.dictionaries.dict_a]
			description = "My first dictionary"
			[setup.dictionaries.dict_a.items.foo]
			value = "my default value for foo"
			description = "a good description about foo"
			[setup.dictionaries.dict_a.items.bar]
			value = "my default value for bar"
			description = "a good description about bar"
			`,
			stdin: []string{
				"Y", // when prompted to create a new service
			},
			wantOutput: []string{
				"Configuring dictionary 'dict_a'",
				"My first dictionary",
				"Create a dictionary key called 'foo'",
				"my default value for foo",
				"Create a dictionary key called 'bar'",
				"my default value for bar",
				"Creating dictionary 'dict_a'...",
				"Creating dictionary item 'foo'...",
				"Creating dictionary item 'bar'...",
				"Uploading package...",
				"Activating version...",
				"SUCCESS: Deployed package (service 12345, version 1)",
			},
		},
		{
			name: "success with setup.dictionaries configuration and no existing service and --non-interactive",
			args: args("compute deploy --non-interactive --token 123"),
			api: mock.API{
				ActivateVersionFn:      activateVersionOk,
				CreateBackendFn:        createBackendOK,
				CreateDictionaryFn:     createDictionaryOK,
				CreateDictionaryItemFn: createDictionaryItemOK,
				CreateDomainFn:         createDomainOK,
				CreateServiceFn:        createServiceOK,
				GetPackageFn:           getPackageOk,
				GetServiceFn:           getServiceOK,
				GetServiceDetailsFn:    getServiceDetailsWasm,
				ListDomainsFn:          listDomainsOk,
				ListVersionsFn:         testutil.ListVersions,
				UpdatePackageFn:        updatePackageOk,
			},
			manifest: `
			name = "package"
			manifest_version = 2
			language = "rust"

			[setup.dictionaries.dict_a]
			description = "My first dictionary"
			[setup.dictionaries.dict_a.items.foo]
			value = "my default value for foo"
			description = "a good description about foo"
			[setup.dictionaries.dict_a.items.bar]
			value = "my default value for bar"
			description = "a good description about bar"
			`,
			stdin: []string{
				"Y", // when prompted to create a new service
			},
			wantOutput: []string{
				"Creating dictionary 'dict_a'...",
				"Creating dictionary item 'foo'...",
				"Creating dictionary item 'bar'...",
				"Uploading package...",
				"Activating version...",
				"SUCCESS: Deployed package (service 12345, version 1)",
			},
		},
		{
			name: "success with setup.dictionaries configuration and no existing service and no predefined values",
			args: args("compute deploy --token 123"),
			api: mock.API{
				ActivateVersionFn:      activateVersionOk,
				CreateBackendFn:        createBackendOK,
				CreateDictionaryFn:     createDictionaryOK,
				CreateDictionaryItemFn: createDictionaryItemOK,
				CreateDomainFn:         createDomainOK,
				CreateServiceFn:        createServiceOK,
				GetPackageFn:           getPackageOk,
				GetServiceFn:           getServiceOK,
				GetServiceDetailsFn:    getServiceDetailsWasm,
				ListDomainsFn:          listDomainsOk,
				ListVersionsFn:         testutil.ListVersions,
				UpdatePackageFn:        updatePackageOk,
			},
			manifest: `
			name = "package"
			manifest_version = 2
			language = "rust"

			[setup.dictionaries.dict_a]
			[setup.dictionaries.dict_a.items.foo]
			[setup.dictionaries.dict_a.items.bar]
			`,
			stdin: []string{
				"Y", // when prompted to create a new service
			},
			wantOutput: []string{
				"Configuring dictionary 'dict_a'",
				"Create a dictionary key called 'foo'",
				"Create a dictionary key called 'bar'",
				"Creating dictionary 'dict_a'...",
				"Creating dictionary item 'foo'...",
				"Creating dictionary item 'bar'...",
				"Uploading package...",
				"Activating version...",
				"SUCCESS: Deployed package (service 12345, version 1)",
			},
			// The following are predefined values for the `description` and `value`
			// fields from the prior setup.dictionaries tests that we expect to not
			// be present in the stdout/stderr as the [setup/dictionaries]
			// configuration does not define them.
			dontWantOutput: []string{
				"My first dictionary",
				"my default value for foo",
				"my default value for bar",
			},
		},
		{
			name: "success with setup.log_entries configuration and existing service",
			args: args("compute deploy --service-id 123 --token 123"),
			api: mock.API{
				ActivateVersionFn:   activateVersionOk,
				CreateBackendFn:     createBackendOK,
				GetPackageFn:        getPackageOk,
				GetServiceFn:        getServiceOK,
				GetServiceDetailsFn: getServiceDetailsWasm,
				ListDomainsFn:       listDomainsOk,
				ListVersionsFn:      testutil.ListVersions,
				UpdatePackageFn:     updatePackageOk,
			},
			manifest: `
			name = "package"
			manifest_version = 2
			language = "rust"

			[setup.log_endpoints.foo]
			provider = "BigQuery"
			`,
			wantOutput: []string{
				"Uploading package...",
				"Activating version...",
				"SUCCESS: Deployed package (service 123, version 3)",
			},
			dontWantOutput: []string{
				"The package code requires the following log endpoints to be created.",
				"Name: foo",
				"Provider: BigQuery",
				"Refer to the help documentation for each provider (if no provider shown, then select your own):",
				"fastly logging <provider> create --help",
			},
		},
		{
			name: "success with setup.log_entries configuration and no existing service",
			args: args("compute deploy --token 123"),
			api: mock.API{
				ActivateVersionFn:      activateVersionOk,
				CreateBackendFn:        createBackendOK,
				CreateDictionaryFn:     createDictionaryOK,
				CreateDictionaryItemFn: createDictionaryItemOK,
				CreateDomainFn:         createDomainOK,
				CreateServiceFn:        createServiceOK,
				GetPackageFn:           getPackageOk,
				GetServiceFn:           getServiceOK,
				GetServiceDetailsFn:    getServiceDetailsWasm,
				ListDomainsFn:          listDomainsOk,
				ListVersionsFn:         testutil.ListVersions,
				UpdatePackageFn:        updatePackageOk,
			},
			manifest: `
			name = "package"
			manifest_version = 2
			language = "rust"

			[setup.log_endpoints.foo]
			provider = "BigQuery"
			`,
			stdin: []string{
				"Y", // when prompted to create a new service
			},
			wantOutput: []string{
				"The package code requires the following log endpoints to be created.",
				"Name: foo",
				"Provider: BigQuery",
				"Refer to the help documentation for each provider (if no provider shown, then select your own):",
				"fastly logging <provider> create --help",
				"Uploading package...",
				"Activating version...",
				"SUCCESS: Deployed package (service 12345, version 1)",
			},
		},
		{
			name: "success with setup.log_entries configuration and no existing service and no provider defined",
			args: args("compute deploy --token 123"),
			api: mock.API{
				ActivateVersionFn:      activateVersionOk,
				CreateBackendFn:        createBackendOK,
				CreateDictionaryFn:     createDictionaryOK,
				CreateDictionaryItemFn: createDictionaryItemOK,
				CreateDomainFn:         createDomainOK,
				CreateServiceFn:        createServiceOK,
				GetPackageFn:           getPackageOk,
				GetServiceFn:           getServiceOK,
				GetServiceDetailsFn:    getServiceDetailsWasm,
				ListDomainsFn:          listDomainsOk,
				ListVersionsFn:         testutil.ListVersions,
				UpdatePackageFn:        updatePackageOk,
			},
			manifest: `
			name = "package"
			manifest_version = 2
			language = "rust"

			[setup.log_endpoints.foo]
			`,
			stdin: []string{
				"Y", // when prompted to create a new service
			},
			wantOutput: []string{
				"The package code requires the following log endpoints to be created.",
				"Name: foo",
				"Refer to the help documentation for each provider (if no provider shown, then select your own):",
				"fastly logging <provider> create --help",
				"Uploading package...",
				"Activating version...",
				"SUCCESS: Deployed package (service 12345, version 1)",
			},
			dontWantOutput: []string{
				"Provider: BigQuery",
			},
		},
		{
			name: "success with setup.log_entries configuration and no existing service, but a provider defined",
			args: args("compute deploy --token 123"),
			api: mock.API{
				ActivateVersionFn:      activateVersionOk,
				CreateBackendFn:        createBackendOK,
				CreateDictionaryFn:     createDictionaryOK,
				CreateDictionaryItemFn: createDictionaryItemOK,
				CreateDomainFn:         createDomainOK,
				CreateServiceFn:        createServiceOK,
				GetPackageFn:           getPackageOk,
				GetServiceFn:           getServiceOK,
				GetServiceDetailsFn:    getServiceDetailsWasm,
				ListDomainsFn:          listDomainsOk,
				ListVersionsFn:         testutil.ListVersions,
				UpdatePackageFn:        updatePackageOk,
			},
			manifest: `
			name = "package"
			manifest_version = 2
			language = "rust"

			[setup.log_endpoints.foo]
			provider = "BigQuery"
			`,
			stdin: []string{
				"Y", // when prompted to create a new service
			},
			wantOutput: []string{
				"The package code requires the following log endpoints to be created.",
				"Name: foo",
				"Provider: BigQuery",
				"Refer to the help documentation for each provider (if no provider shown, then select your own):",
				"fastly logging <provider> create --help",
				"Uploading package...",
				"Activating version...",
				"SUCCESS: Deployed package (service 12345, version 1)",
			},
		},
	} {
		t.Run(testcase.name, func(t *testing.T) {
			// Because the manifest can be mutated on each test scenario, we recreate
			// the file each time.
			manifestContent := `manifest_version = 2
			name = "package"			
			`
			if testcase.manifest != "" {
				manifestContent = testcase.manifest
			}
			if err := os.WriteFile(filepath.Join(rootdir, manifest.Filename), []byte(manifestContent), 0o777); err != nil {
				t.Fatal(err)
			}

			// For any test scenario that expects no manifest to exist, then instead
			// of deleting the manifest and having to recreate it, we'll simply
			// rename it, and then rename it back once the specific test scenario has
			// finished running.
			if testcase.noManifest {
				old := filepath.Join(rootdir, manifest.Filename)
				tmp := filepath.Join(rootdir, manifest.Filename+"Tmp")
				if err := os.Rename(old, tmp); err != nil {
					t.Fatal(err)
				}
				defer func() {
					if err := os.Rename(tmp, old); err != nil {
						t.Fatal(err)
					}
				}()
			}

			var stdout bytes.Buffer
			opts := testutil.NewRunOpts(testcase.args, &stdout)
			opts.APIClient = mock.APIClient(testcase.api)

			if testcase.httpClientRes != nil || testcase.httpClientErr != nil {
				opts.HTTPClient = mock.HTMLClient(testcase.httpClientRes, testcase.httpClientErr)
			}

			if testcase.reduceSizeLimit {
				compute.PackageSizeLimit = 1000000 // 1mb (our test package should above this)
			} else {
				// As multiple test scenarios run within a single environment instance
				// we need to ensure each scenario resets the package variable.
				compute.PackageSizeLimit = originalPackageSizeLimit
			}

			if len(testcase.stdin) > 1 {
				// To handle multiple prompt input from the user we need to do some
				// coordination around io pipes to mimic the required user behaviour.
				stdin, prompt := io.Pipe()
				opts.Stdin = stdin

				// Wait for user input and write it to the prompt
				inputc := make(chan string)
				go func() {
					for input := range inputc {
						fmt.Fprintln(prompt, input)
					}
				}()

				// We need a channel so we wait for `run()` to complete
				done := make(chan bool)

				// Call `app.Run()` and wait for response
				go func() {
					err = app.Run(opts)
					done <- true
				}()

				// User provides input
				//
				// NOTE: Must provide as much input as is expected to be waited on by `run()`.
				//       For example, if `run()` calls `input()` twice, then provide two messages.
				//       Otherwise the select statement will trigger the timeout error.
				for _, input := range testcase.stdin {
					inputc <- input
				}

				select {
				case <-done:
					// Wait for app.Run() to finish
				case <-time.After(time.Second):
					t.Fatalf("unexpected timeout waiting for mocked prompt inputs to be processed")
				}
			} else {
				stdin := ""
				if len(testcase.stdin) > 0 {
					stdin = testcase.stdin[0]
				}
				opts.Stdin = strings.NewReader(stdin)
				err = app.Run(opts)
			}

			t.Log(stdout.String())

			testutil.AssertErrorContains(t, err, testcase.wantError)
			testutil.AssertRemediationErrorContains(t, err, testcase.wantRemediationError)

			for _, s := range testcase.wantOutput {
				testutil.AssertStringContains(t, stdout.String(), s)
			}

			for _, s := range testcase.dontWantOutput {
				testutil.AssertStringDoesntContain(t, stdout.String(), s)
			}
		})
	}
}

func createServiceOK(i *fastly.CreateServiceInput) (*fastly.Service, error) {
	return &fastly.Service{
		ID:   "12345",
		Name: i.Name,
		Type: i.Type,
	}, nil
}

func createServiceError(*fastly.CreateServiceInput) (*fastly.Service, error) {
	return nil, testutil.Err
}

// NOTE: We don't return testutil.Err but a very specific error message so that
// the Deploy logic will drop into a nested logic block.
func createServiceErrorNoTrial(*fastly.CreateServiceInput) (*fastly.Service, error) {
	return nil, fmt.Errorf("Valid values for 'type' are: 'vcl'")
}

func getCurrentUser() (*fastly.User, error) {
	return &fastly.User{
		CustomerID: "abc",
	}, nil
}

func getCurrentUserError() (*fastly.User, error) {
	return nil, testutil.Err
}

func deleteServiceOK(i *fastly.DeleteServiceInput) error {
	return nil
}

func createDomainError(i *fastly.CreateDomainInput) (*fastly.Domain, error) {
	return nil, testutil.Err
}

func deleteDomainOK(i *fastly.DeleteDomainInput) error {
	return nil
}

func createBackendError(i *fastly.CreateBackendInput) (*fastly.Backend, error) {
	return nil, testutil.Err
}

func deleteBackendOK(i *fastly.DeleteBackendInput) error {
	return nil
}

func getPackageIdentical(i *fastly.GetPackageInput) (*fastly.Package, error) {
	return &fastly.Package{
		ServiceID:      i.ServiceID,
		ServiceVersion: i.ServiceVersion,
		Metadata: fastly.PackageMetadata{
			HashSum: "84b2bbb700142d16ed7efad2058984ee01881654effca70dfe7f21ec8b451df12e49173569145d2920e6449745bf87ede2a68c73e2e165c2d1190d469f99046f",
		},
	}, nil
}

func activateVersionError(i *fastly.ActivateVersionInput) (*fastly.Version, error) {
	return nil, testutil.Err
}

func listDomainsError(i *fastly.ListDomainsInput) ([]*fastly.Domain, error) {
	return nil, testutil.Err
}

func listDomainsNone(i *fastly.ListDomainsInput) ([]*fastly.Domain, error) {
	return []*fastly.Domain{}, nil
}
