name: Build CLI Binaries
on:
  pull_request:
    branches:
      - "main"
    types:
      [closed]
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true
jobs:
  build:
    name: Build CLI (${{ matrix.platform }})
    if: ${{ github.event.pull_request.merged }}
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: "Checkout code"
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: "Install Node"
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 18
      - name: "Install Rust"
        uses: actions-rust-lang/setup-rust-toolchain@166cdcfd11aee3cb47222f9ddb555ce30ddb9659 # v1.17.0
        with:
          toolchain: stable
          cache: false
          rustflags: ""
      - name: Install Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: 1.25.x
      - name: "Install dependencies"
        run: make mod-download
        shell: bash
      - name: "Create Build"
        run: make build
        shell: bash
      - name: "Upload Build"
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: fastly-cli-build-${{ matrix.platform }}-${{ github.sha }}
          path: fastly
