name: Draft Release from Tag
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false
jobs:
  goreleaser:
    name: Run goreleaser
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: "Checkout code"
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: "Fetch unshallow repo"
        run: git fetch --prune --unshallow
      - name: "Install Go"
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: '1.26.x'
          cache: false
      - name: "Install Rust"
        uses: actions-rust-lang/setup-rust-toolchain@166cdcfd11aee3cb47222f9ddb555ce30ddb9659 # v1.17.0
        with:
          toolchain: stable
          cache: false
          rustflags: ""
      - name: "Generate static app config"
        run: make config
      - name: "Run GoReleaser"
        uses: goreleaser/goreleaser-action@f06c13b6b1a9625abc9e6e439d9c05a8f2190e94 # v7.2.3
        with:
          # goreleaser version (NOT goreleaser-action version)
          # update inline with the Makefile
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "Upload Homebrew formula as artifact"
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: homebrew-formula-${{ github.ref_name }}
          path: dist/homebrew/Formula/fastly.rb
          if-no-files-found: error
