name: Draft Release from Tag
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false
jobs:
  goreleaser:
    name: Run goreleaser
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: "Fetch unshallow repo"
        run: git fetch --prune --unshallow
      - name: "Install Go"
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version: '1.26.x'
          cache: false
      - name: "Install Rust"
        uses: actions-rust-lang/setup-rust-toolchain@46268bd060767258de96ed93c1251119784f2ab6 # v1.16.1
        with:
          toolchain: stable
          cache: false
          rustflags: ""
      - name: "Generate static app config"
        run: make config
      # Passing the raw SSH private key causes an error:
      # Load key "/tmp/id_*": invalid format
      #
      # Testing locally we discovered that storing in a file and passing the file path works.
      #
      # NOTE:
      # The file aur_key must be added to .gitignore otherwise a 'dirty state' error is triggered in goreleaser.
      # https://github.com/goreleaser/goreleaser/blob/9505cf7054b05a6e9a4a36f806d525bc33660e9e/www/docs/errors/dirty.md
      #
      # You must also reduce the permissions from a default of 0644 to 600 to avoid a 'bad permissions' error.
      - name: "Store AUR_KEY in local file"
        env:
          AUR_KEY_SECRET: ${{ secrets.AUR_KEY }}
        run: |
          printf '%s\n' "$AUR_KEY_SECRET" > "$GITHUB_WORKSPACE/aur_key"
          chmod 600 "$GITHUB_WORKSPACE/aur_key"
      - name: "Run GoReleaser"
        uses: goreleaser/goreleaser-action@5daf1e915a5f0af01ddbcd89a43b8061ff4f1a89 # v7.2.2
        with:
          # goreleaser version (NOT goreleaser-action version)
          # update inline with the Makefile
          version: '~> v2'
          args: release --clean
        env:
          AUR_KEY: '${{ github.workspace }}/aur_key'
          GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
